/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "AttributeApi.h"
#include "../model/Helpers.h"

namespace inexor {
namespace entity_system {
namespace server {
namespace api {

using namespace inexor::entity_system::server::helpers;
using namespace inexor::entity_system::server::model;

AttributeApi::AttributeApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void AttributeApi::init() {
    setupRoutes();
}

void AttributeApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/entities/instances/:entity_instance_uuid/attributes/:name", Routes::bind(&AttributeApi::create_or_update_entity_instance_attribute_handler, this));
    Routes::Post(*router, base + "/entities/types/:entity_type_uuid/attributes/:name", Routes::bind(&AttributeApi::create_or_update_entity_type_attribute_handler, this));
    Routes::Delete(*router, base + "/entities/instances/:entity_instance_uuid/attributes/:name", Routes::bind(&AttributeApi::delete_entity_instance_attribute_handler, this));
    Routes::Delete(*router, base + "/entities/types/:entity_type_uuid/attributes/:name", Routes::bind(&AttributeApi::delete_entity_type_attribute_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/attributes/:name", Routes::bind(&AttributeApi::get_entity_instance_attribute_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/attributes", Routes::bind(&AttributeApi::get_entity_instance_attributes_handler, this));
    Routes::Get(*router, base + "/entities/types/:entity_type_uuid/attributes/:name", Routes::bind(&AttributeApi::get_entity_type_attribute_handler, this));
    Routes::Get(*router, base + "/entities/types/:entity_type_uuid/attributes", Routes::bind(&AttributeApi::get_entity_type_attributes_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&AttributeApi::attribute_api_default_handler, this));
}

void AttributeApi::create_or_update_entity_instance_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    auto name = request.param(":name").as<std::string>();
    
    // Getting the body param
    
    Attribute attribute;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      attribute.fromJson(request_body);
    
      this->create_or_update_entity_instance_attribute(entityInstanceUuid, name, attribute, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AttributeApi::create_or_update_entity_type_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityTypeUuid = request.param(":entityTypeUuid").as<std::string>();
    auto name = request.param(":name").as<std::string>();
    
    // Getting the body param
    
    std::string body;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      // The conversion is done automatically by the json library
      body = request_body;
      this->create_or_update_entity_type_attribute(entityTypeUuid, name, body, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AttributeApi::delete_entity_instance_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    auto name = request.param(":name").as<std::string>();
    
    try {
      this->delete_entity_instance_attribute(entityInstanceUuid, name, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AttributeApi::delete_entity_type_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityTypeUuid = request.param(":entityTypeUuid").as<std::string>();
    auto name = request.param(":name").as<std::string>();
    
    try {
      this->delete_entity_type_attribute(entityTypeUuid, name, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AttributeApi::get_entity_instance_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    auto name = request.param(":name").as<std::string>();
    
    try {
      this->get_entity_instance_attribute(entityInstanceUuid, name, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AttributeApi::get_entity_instance_attributes_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    
    try {
      this->get_entity_instance_attributes(entityInstanceUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AttributeApi::get_entity_type_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityTypeUuid = request.param(":entityTypeUuid").as<std::string>();
    auto name = request.param(":name").as<std::string>();
    
    try {
      this->get_entity_type_attribute(entityTypeUuid, name, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void AttributeApi::get_entity_type_attributes_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityTypeUuid = request.param(":entityTypeUuid").as<std::string>();
    
    try {
      this->get_entity_type_attributes(entityTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void AttributeApi::attribute_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

