/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AttributeApi.h
 *
 * 
 */

#ifndef AttributeApi_H_
#define AttributeApi_H_


#include <string>

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>

#include "../model/Attribute.h"
#include "../model/EntitySystemMessage.h"
#include "../model/EntityType.h"

namespace inexor {
namespace entity_system {
namespace server {
namespace api {

using namespace inexor::entity_system::server::model;

class  AttributeApi {
public:
    AttributeApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~AttributeApi() {}
    void init();

    const std::string base = "/api/v1";

private:
    void setupRoutes();

    void create_or_update_entity_instance_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void create_or_update_entity_type_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void delete_entity_instance_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void delete_entity_type_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_entity_instance_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_entity_instance_attributes_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_entity_type_attribute_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_entity_type_attributes_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void attribute_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Creates (or updates if already exists) the attribute of the entity instance
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityInstanceUuid">The UUID of the entity instance</param>
    /// <param name="name">The name of the attribute</param>
    /// <param name="attribute">The attribute as object</param>
    virtual void create_or_update_entity_instance_attribute(const std::string &entityInstanceUuid, const std::string &name, const Attribute &attribute, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Creates (or updates if already exists) the value of the named attribute of the entity type with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityTypeUuid">The UUID of the entity type to retrieve</param>
    /// <param name="name">The name of the attribute</param>
    /// <param name="body">The entity type as object</param>
    virtual void create_or_update_entity_type_attribute(const std::string &entityTypeUuid, const std::string &name, const std::string &body, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Deletes the attribute of the entity instance
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityInstanceUuid">The UUID of the entity instance</param>
    /// <param name="name">The name of the attribute</param>
    virtual void delete_entity_instance_attribute(const std::string &entityInstanceUuid, const std::string &name, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Deletes the named attribute of the entity type with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityTypeUuid">The UUID of the entity type to retrieve</param>
    /// <param name="name">The name of the attribute</param>
    virtual void delete_entity_type_attribute(const std::string &entityTypeUuid, const std::string &name, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns the value of the named attribute of the entity instance
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityInstanceUuid">The UUID of the entity instance</param>
    /// <param name="name">The name of the attribute</param>
    virtual void get_entity_instance_attribute(const std::string &entityInstanceUuid, const std::string &name, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns all attributes of the entity instance with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityInstanceUuid">The UUID of the entity instance</param>
    virtual void get_entity_instance_attributes(const std::string &entityInstanceUuid, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns the value of the named attribute of the entity type with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityTypeUuid">The UUID of the entity type to retrieve</param>
    /// <param name="name">The name of the attribute</param>
    virtual void get_entity_type_attribute(const std::string &entityTypeUuid, const std::string &name, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns all attributes of the given entity type with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityTypeUuid">The UUID of the entity type to retrieve</param>
    virtual void get_entity_type_attributes(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* AttributeApi_H_ */

