/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EntitySystemApi.h
 *
 * 
 */

#ifndef EntitySystemApi_H_
#define EntitySystemApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "../model/EntitySystem.h"
#include "../model/EntitySystemMessage.h"

namespace inexor {
namespace entity_system {
namespace server {
namespace api {

using namespace inexor::entity_system::server::model;

class  EntitySystemApi {
public:
    EntitySystemApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~EntitySystemApi() {}
    void init();

    const std::string base = "/api/v1";

private:
    void setupRoutes();

    void clearntity_system_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void export_entity_system_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void import_entity_system_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void entity_system_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Clears the whole entity system
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    virtual void clearntity_system(Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Exports the whole entity system
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    virtual void export_entity_system(Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Imports the whole entity system
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    virtual void import_entity_system(Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* EntitySystemApi_H_ */

