/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EntitySystemApi.h
 *
 * 
 */

#ifndef EntitySystemApi_H_
#define EntitySystemApi_H_


#include <memory>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/service.hpp>

#include "../model/EntitySystem.h"
#include "../model/EntitySystemMessage.h"

namespace inexor {
namespace entity_system {
namespace rest {
namespace api {

using namespace inexor::entity_system::rest::model;

class  EntitySystemApi: public restbed::Service
{
public:
	EntitySystemApi();
	~EntitySystemApi();
	void startService(int const& port);
	void stopService();
};


/// <summary>
/// Clears the whole entity system
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  EntitySystemApiEntitysystemResource: public restbed::Resource
{
public:
	EntitySystemApiEntitysystemResource();
    virtual ~EntitySystemApiEntitysystemResource();
    void DELETE_method_handler(const std::shared_ptr<restbed::Session> session);
    void GET_method_handler(const std::shared_ptr<restbed::Session> session);
    void POST_method_handler(const std::shared_ptr<restbed::Session> session);
};


}
}
}
}

#endif /* EntitySystemApi_H_ */

