/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include <crossguid/guid.hpp>
#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>

#include "EntityTypeApi.h"

namespace inexor {
namespace entity_system {
namespace rest {
namespace api {

using namespace inexor::entity_system::rest::model;
using namespace xg;
using namespace restbed;
using namespace std;

EntityTypeApi::EntityTypeApi() {
}

EntityTypeApi::~EntityTypeApi() {}

void EntityTypeApi::createResources(std::shared_ptr<inexor::entity_system::EntitySystem> entity_system, std::shared_ptr<Service> service) {
	shared_ptr<EntityTypeApiEntitiesTypesResource> spEntityTypeApiEntitiesTypesResource = make_shared<EntityTypeApiEntitiesTypesResource>(entity_system);
	service->publish(spEntityTypeApiEntitiesTypesResource);
	
	shared_ptr<EntityTypeApiEntitiesTypesEntity_type_uuidResource> spEntityTypeApiEntitiesTypesEntity_type_uuidResource = make_shared<EntityTypeApiEntitiesTypesEntity_type_uuidResource>(entity_system);
	service->publish(spEntityTypeApiEntitiesTypesEntity_type_uuidResource);
	
	shared_ptr<EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource> spEntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource = make_shared<EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource>(entity_system);
	service->publish(spEntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource);
	
	shared_ptr<EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource> spEntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource = make_shared<EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource>(entity_system);
	service->publish(spEntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource);
	
	shared_ptr<EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource> spEntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource = make_shared<EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource>(entity_system);
	service->publish(spEntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource);
	
	shared_ptr<EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource> spEntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource = make_shared<EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource>(entity_system);
	service->publish(spEntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource);
	
	shared_ptr<EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource> spEntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource = make_shared<EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource>(entity_system);
	service->publish(spEntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource);
	
	shared_ptr<EntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource> spEntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource = make_shared<EntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource>(entity_system);
	service->publish(spEntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource);
}

/**
 * Defines the method handlers for route /entities/types/
 */
EntityTypeApiEntitiesTypesResource::EntityTypeApiEntitiesTypesResource(shared_ptr<inexor::entity_system::EntitySystem> entity_system)
{
	this->entity_system = entity_system;
	this->set_path("/entities/types/");
	this->set_method_handler("POST", bind(&EntityTypeApiEntitiesTypesResource::POST_method_handler, this, placeholders::_1));
	this->set_method_handler("DELETE", bind(&EntityTypeApiEntitiesTypesResource::DELETE_method_handler, this, placeholders::_1));
	this->set_method_handler("GET", bind(&EntityTypeApiEntitiesTypesResource::GET_method_handler, this, placeholders::_1));
}

EntityTypeApiEntitiesTypesResource::~EntityTypeApiEntitiesTypesResource()
{
}

/**
 * TODO: Creates an entity type.
 */
void EntityTypeApiEntitiesTypesResource::POST_method_handler(const shared_ptr<Session> session) {
	cout << "[POST] /entities/types/" << endl;

	const auto request = session->get_request();

	// TODO: implement
	auto entity_type = this->entity_system->create_entity_type("");

			
	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * TODO: Create new entity type using POST body.
	 */

	if (status_code == 200) {
		session->close(200, "The created entity type", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}

/**
 * Deletes all entity types (and all entity instances).
 * DONE.
 */
void EntityTypeApiEntitiesTypesResource::DELETE_method_handler(const shared_ptr<Session> session) {
	cout << "[DELETE] /entities/types/" << endl;
	const auto request = session->get_request();
	int status_code = 200;
	entity_system->delete_all_entity_types();
	if (status_code == 200) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(200, "Success message", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}
}

/**
 * TODO: Lists all entity types.
 */
void EntityTypeApiEntitiesTypesResource::GET_method_handler(const shared_ptr<Session> session) {
	cout << "[GET] /entities/types/" << endl;
	const auto request = session->get_request();
	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;
	/**
	 * Process the received information here
	 */
	if (status_code == 200) {
		shared_ptr<EntityType> response = NULL;
		session->close(200, "A list of entity types", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}
}

/**
 * Defines the method handlers for route /entities/types/{entity_type_uuid}/
 */
EntityTypeApiEntitiesTypesEntity_type_uuidResource::EntityTypeApiEntitiesTypesEntity_type_uuidResource(shared_ptr<inexor::entity_system::EntitySystem> entity_system)
{
	this->entity_system = entity_system;
	this->set_path("/entities/types/{entity_type_uuid: .*}/");
	this->set_method_handler("POST", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidResource::POST_method_handler, this, placeholders::_1));
	this->set_method_handler("DELETE", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidResource::DELETE_method_handler, this, placeholders::_1));
	this->set_method_handler("GET", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidResource::GET_method_handler, this, placeholders::_1));
}

EntityTypeApiEntitiesTypesEntity_type_uuidResource::~EntityTypeApiEntitiesTypesEntity_type_uuidResource()
{
}

void EntityTypeApiEntitiesTypesEntity_type_uuidResource::POST_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();
	// Body params are present, therefore we have to fetch them
	int content_length = request->get_header("Content-Length", 0);
	session->fetch(content_length,
		[ this ]( const shared_ptr<Session> session, const Bytes & body )
		{

			const auto request = session->get_request();
			string requestBody = String::format("%.*s\n", ( int ) body.size( ), body.data( ));
			/**
			 * Get body params or form params here from the requestBody string
			 */
			
			// Getting the path params
			const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");
			

			
			// Change the value of this variable to the appropriate response before sending the response
			int status_code = 200;
			
			/**
			 * Process the received information here
			 */
			
			if (status_code == 200) {
				session->close(200, "An entity type", { {"Connection", "close"} });
				return;
			}
			if (status_code == 0) {
				session->close(0, "unexpected error", { {"Connection", "close"} });
				return;
			}

		});
}

void EntityTypeApiEntitiesTypesEntity_type_uuidResource::DELETE_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */
	// entity_system->delete_entity_type(g(entityTypeUuid));

	if (status_code == 200) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(200, "Success message", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}
void EntityTypeApiEntitiesTypesEntity_type_uuidResource::GET_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		shared_ptr<EntityType> response = NULL;
		session->close(200, "An entity type", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}


EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource::EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource(shared_ptr<inexor::entity_system::EntitySystem> entity_system)
{
	this->entity_system = entity_system;
	this->set_path("/entities/types/{entity_type_uuid: .*}/attributes/{name: .*}/");
	this->set_method_handler("POST", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource::POST_method_handler, this, placeholders::_1));
	this->set_method_handler("DELETE", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource::DELETE_method_handler, this, placeholders::_1));
	this->set_method_handler("GET", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource::GET_method_handler, this, placeholders::_1));
}

EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource::~EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource()
{
}

void EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource::POST_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();
	// Body params are present, therefore we have to fetch them
	int content_length = request->get_header("Content-Length", 0);
	session->fetch(content_length,
		[ this ]( const shared_ptr<Session> session, const Bytes & body )
		{

			const auto request = session->get_request();
			string requestBody = String::format("%.*s\n", ( int ) body.size( ), body.data( ));
			/**
			 * Get body params or form params here from the requestBody string
			 */
			
			// Getting the path params
			const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");
			const string name = request->get_path_parameter("name", "");
			

			
			// Change the value of this variable to the appropriate response before sending the response
			int status_code = 200;
			
			/**
			 * Process the received information here
			 */
			
			if (status_code == 200) {
				session->close(200, "An entity type", { {"Connection", "close"} });
				return;
			}
			if (status_code == 0) {
				session->close(0, "unexpected error", { {"Connection", "close"} });
				return;
			}

		});
}

void EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource::DELETE_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");
	const string name = request->get_path_parameter("name", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	// Guid g(entityTypeUuid);
	// auto entity_type = entity_system->get_type(g(entityTypeUuid));
	// auto attribute_type = entity_type->get_attribute_by_name(name);
	// entity_system->delete_entity_attribute_type(attribute_type->get_uuid());

	if (status_code == 200) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(200, "Success message", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}
void EntityTypeApiEntitiesTypesEntity_type_uuidAttributesNameResource::GET_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");
	const string name = request->get_path_parameter("name", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		shared_ptr<Attribute> response = NULL;
		session->close(200, "The attribute", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}


EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource::EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource(shared_ptr<inexor::entity_system::EntitySystem> entity_system)
{
	this->entity_system = entity_system;
	this->set_path("/entities/types/{entity_type_uuid: .*}/instances/");
	this->set_method_handler("DELETE", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource::DELETE_method_handler, this, placeholders::_1));
	this->set_method_handler("GET", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource::GET_method_handler, this, placeholders::_1));
}

EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource::~EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource()
{
}

void EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource::DELETE_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "Success message", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}

void EntityTypeApiEntitiesTypesEntity_type_uuidInstancesResource::GET_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		shared_ptr<EntityInstance> response = NULL;
		session->close(200, "Array of entity instances", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		shared_ptr<EntitySystemMessage> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}


EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource::EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource(shared_ptr<inexor::entity_system::EntitySystem> entity_system)
{
	this->entity_system = entity_system;
	this->set_path("/entities/types/{entity_type_uuid: .*}/relationships/incoming/");
	this->set_method_handler("GET", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource::GET_method_handler, this, placeholders::_1));
}

EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource::~EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource()
{
}

void EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsIncomingResource::GET_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "The incoming relationship types", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}



EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource::EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource(shared_ptr<inexor::entity_system::EntitySystem> entity_system)
{
	this->entity_system = entity_system;
	this->set_path("/entities/types/{entity_type_uuid: .*}/relationships/outgoing/");
	this->set_method_handler("GET", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource::GET_method_handler, this, placeholders::_1));
}

EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource::~EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource()
{
}

void EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsOutgoingResource::GET_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "The outgoing relationship types", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}



EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource::EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource(shared_ptr<inexor::entity_system::EntitySystem> entity_system)
{
	this->entity_system = entity_system;
	this->set_path("/entities/types/{entity_type_uuid: .*}/relationships/");
	this->set_method_handler("GET", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource::GET_method_handler, this, placeholders::_1));
}

EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource::~EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource()
{
}

void EntityTypeApiEntitiesTypesEntity_type_uuidRelationshipsResource::GET_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "The incoming and outgoing relationship types", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}



EntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource::EntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource(shared_ptr<inexor::entity_system::EntitySystem> entity_system)
{
	this->entity_system = entity_system;
	this->set_path("/entities/types/{entity_type_uuid: .*}/attributes/");
	this->set_method_handler("GET", bind(&EntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource::GET_method_handler, this, placeholders::_1));
}

EntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource::~EntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource()
{
}

void EntityTypeApiEntitiesTypesEntity_type_uuidAttributesResource::GET_method_handler(const shared_ptr<Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const string entityTypeUuid = request->get_path_parameter("entityTypeUuid", "");



	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "An array of attributes", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}




}
}
}
}

