/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "RelationshipTypeApi.h"
#include "../model/Helpers.h"

namespace inexor {
namespace entity_system {
namespace server {
namespace api {

using namespace inexor::entity_system::server::helpers;
using namespace inexor::entity_system::server::model;

RelationshipTypeApi::RelationshipTypeApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void RelationshipTypeApi::init() {
    setupRoutes();
}

void RelationshipTypeApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/relationships/types/:relationship_type_uuid", Routes::bind(&RelationshipTypeApi::create_or_update_relationship_type_handler, this));
    Routes::Post(*router, base + "/relationships/types", Routes::bind(&RelationshipTypeApi::create_relationship_type_handler, this));
    Routes::Delete(*router, base + "/relationships/types", Routes::bind(&RelationshipTypeApi::delete_all_relationship_types_handler, this));
    Routes::Delete(*router, base + "/relationships/types/:relationship_type_uuid", Routes::bind(&RelationshipTypeApi::delete_relationship_type_handler, this));
    Routes::Get(*router, base + "/entities/types/:entity_type_uuid/relationships/incoming", Routes::bind(&RelationshipTypeApi::get_all_incoming_relationship_types_of_entity_type_handler, this));
    Routes::Get(*router, base + "/entities/types/:entity_type_uuid/relationships/outgoing", Routes::bind(&RelationshipTypeApi::get_all_outgoing_relationship_types_of_entity_type_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/relationships/:relationship_type_uuid", Routes::bind(&RelationshipTypeApi::get_all_relationship_instances_by_relationship_type_of_entity_instance_handler, this));
    Routes::Get(*router, base + "/relationships/types", Routes::bind(&RelationshipTypeApi::get_all_relationship_types_handler, this));
    Routes::Get(*router, base + "/entities/types/:entity_type_uuid/relationships", Routes::bind(&RelationshipTypeApi::get_all_relationship_types_of_entity_type_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/relationships/:relationship_type_uuid/incoming", Routes::bind(&RelationshipTypeApi::get_incoming_relationship_instances_by_relationship_type_of_entity_instance_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/relationships/:relationship_type_uuid/outgoing", Routes::bind(&RelationshipTypeApi::get_outgoing_relationship_instances_by_relationship_type_of_entity_instance_handler, this));
    Routes::Get(*router, base + "/relationships/types/:relationship_type_uuid", Routes::bind(&RelationshipTypeApi::get_relationship_type_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&RelationshipTypeApi::relationship_type_api_default_handler, this));
}

void RelationshipTypeApi::create_or_update_relationship_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto relationshipTypeUuid = request.param(":relationshipTypeUuid").as<std::string>();
    
    // Getting the body param
    
    RelationshipType relationshipType;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      relationshipType.fromJson(request_body);
    
      this->create_or_update_relationship_type(relationshipTypeUuid, relationshipType, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::create_relationship_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the body param
    
    RelationshipType relationshipType;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      relationshipType.fromJson(request_body);
    
      this->create_relationship_type(relationshipType, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::delete_all_relationship_types_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    try {
      this->delete_all_relationship_types(response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::delete_relationship_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto relationshipTypeUuid = request.param(":relationshipTypeUuid").as<std::string>();
    
    try {
      this->delete_relationship_type(relationshipTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::get_all_incoming_relationship_types_of_entity_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityTypeUuid = request.param(":entityTypeUuid").as<std::string>();
    
    try {
      this->get_all_incoming_relationship_types_of_entity_type(entityTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::get_all_outgoing_relationship_types_of_entity_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityTypeUuid = request.param(":entityTypeUuid").as<std::string>();
    
    try {
      this->get_all_outgoing_relationship_types_of_entity_type(entityTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::get_all_relationship_instances_by_relationship_type_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    auto relationshipTypeUuid = request.param(":relationshipTypeUuid").as<std::string>();
    
    try {
      this->get_all_relationship_instances_by_relationship_type_of_entity_instance(entityInstanceUuid, relationshipTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::get_all_relationship_types_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    try {
      this->get_all_relationship_types(response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::get_all_relationship_types_of_entity_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityTypeUuid = request.param(":entityTypeUuid").as<std::string>();
    
    try {
      this->get_all_relationship_types_of_entity_type(entityTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::get_incoming_relationship_instances_by_relationship_type_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    auto relationshipTypeUuid = request.param(":relationshipTypeUuid").as<std::string>();
    
    try {
      this->get_incoming_relationship_instances_by_relationship_type_of_entity_instance(entityInstanceUuid, relationshipTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::get_outgoing_relationship_instances_by_relationship_type_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    auto relationshipTypeUuid = request.param(":relationshipTypeUuid").as<std::string>();
    
    try {
      this->get_outgoing_relationship_instances_by_relationship_type_of_entity_instance(entityInstanceUuid, relationshipTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipTypeApi::get_relationship_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto relationshipTypeUuid = request.param(":relationshipTypeUuid").as<std::string>();
    
    try {
      this->get_relationship_type(relationshipTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void RelationshipTypeApi::relationship_type_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

