/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RelationshipTypeApi.h
 *
 * 
 */

#ifndef RelationshipTypeApi_H_
#define RelationshipTypeApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "../model/EntitySystemMessage.h"
#include "../model/RelationshipInstance.h"
#include "../model/RelationshipType.h"
#include <string>

namespace inexor {
namespace entity_system {
namespace server {
namespace api {

using namespace inexor::entity_system::server::model;

class  RelationshipTypeApi {
public:
    RelationshipTypeApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~RelationshipTypeApi() {}
    void init();

    const std::string base = "/api/v1";

private:
    void setupRoutes();

    void create_or_update_relationship_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void create_relationship_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void delete_all_relationship_types_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void delete_relationship_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_all_incoming_relationship_types_of_entity_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_all_outgoing_relationship_types_of_entity_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_all_relationship_instances_by_relationship_type_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_all_relationship_types_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_all_relationship_types_of_entity_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_incoming_relationship_instances_by_relationship_type_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_outgoing_relationship_instances_by_relationship_type_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void get_relationship_type_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void relationship_type_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Creates or updates a relationship type
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="relationshipTypeUuid">The UUID of the relationship type to create or update</param>
    /// <param name="relationshipType">The relationship type as object</param>
    virtual void create_or_update_relationship_type(const std::string &relationshipTypeUuid, const RelationshipType &relationshipType, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Creates a relationship type
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="relationshipType">The relationship type as object</param>
    virtual void create_relationship_type(const RelationshipType &relationshipType, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Deletes all relationship types (and all relationship instances)
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    virtual void delete_all_relationship_types(Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Deletes the relationship type with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="relationshipTypeUuid">The UUID of the relationship type to delete</param>
    virtual void delete_relationship_type(const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns all incoming relationship types of the entity type with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityTypeUuid">The UUID of the entity type to retrieve</param>
    virtual void get_all_incoming_relationship_types_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns all outgoing relationship types of the entity type with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityTypeUuid">The UUID of the entity type to retrieve</param>
    virtual void get_all_outgoing_relationship_types_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns all incoming and outgoing relationship instances of a certain relationship type
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityInstanceUuid">The UUID of the entity instance</param>
    /// <param name="relationshipTypeUuid">The UUID of the relationship type</param>
    virtual void get_all_relationship_instances_by_relationship_type_of_entity_instance(const std::string &entityInstanceUuid, const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns all relationship types
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    virtual void get_all_relationship_types(Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns all incoming and outgoing relationship types of the entity type with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityTypeUuid">The UUID of the entity type to retrieve</param>
    virtual void get_all_relationship_types_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns all incoming and outgoing relationship instances of a certain relationship type
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityInstanceUuid">The UUID of the entity instance</param>
    /// <param name="relationshipTypeUuid">The UUID of the relationship type</param>
    virtual void get_incoming_relationship_instances_by_relationship_type_of_entity_instance(const std::string &entityInstanceUuid, const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns all incoming and outgoing relationship instances of a certain relationship type
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="entityInstanceUuid">The UUID of the entity instance</param>
    /// <param name="relationshipTypeUuid">The UUID of the relationship type</param>
    virtual void get_outgoing_relationship_instances_by_relationship_type_of_entity_instance(const std::string &entityInstanceUuid, const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response) = 0;

    /// <summary>
    /// Returns the relationship type with the given UUID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="relationshipTypeUuid">The UUID of the relationship type to retrieve</param>
    virtual void get_relationship_type(const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* RelationshipTypeApi_H_ */

