/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "RelationshipInstanceApi.h"
#include "../model/Helpers.h"

namespace inexor {
namespace entity_system {
namespace server {
namespace api {

using namespace inexor::entity_system::server::helpers;
using namespace inexor::entity_system::server::model;

RelationshipInstanceApi::RelationshipInstanceApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void RelationshipInstanceApi::init() {
    setupRoutes();
}

void RelationshipInstanceApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/relationships/instances/:relationship_instance_uuid", Routes::bind(&RelationshipInstanceApi::create_or_update_relationship_instance_handler, this));
    Routes::Post(*router, base + "/relationships/instances", Routes::bind(&RelationshipInstanceApi::create_relationship_instance_handler, this));
    Routes::Delete(*router, base + "/relationships/instances", Routes::bind(&RelationshipInstanceApi::delete_all_relationship_instances_handler, this));
    Routes::Delete(*router, base + "/relationships/instances/:relationship_instance_uuid", Routes::bind(&RelationshipInstanceApi::delete_relationship_instance_handler, this));
    Routes::Delete(*router, base + "/relationships/instances/start/:start_entity_instance_uuid/end/:end_entity_instance_uuid", Routes::bind(&RelationshipInstanceApi::delete_relationship_instances_between_start_and_end_handler, this));
    Routes::Get(*router, base + "/relationships/instances", Routes::bind(&RelationshipInstanceApi::get_all_relationship_instances_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/relationships/:relationship_type_uuid", Routes::bind(&RelationshipInstanceApi::get_all_relationship_instances_by_relationship_type_of_entity_instance_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/relationships", Routes::bind(&RelationshipInstanceApi::get_all_relationship_instances_of_entity_instance_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/relationships/:relationship_type_uuid/incoming", Routes::bind(&RelationshipInstanceApi::get_incoming_relationship_instances_by_relationship_type_of_entity_instance_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/relationships/incoming", Routes::bind(&RelationshipInstanceApi::get_incoming_relationship_instances_of_entity_instance_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/relationships/:relationship_type_uuid/outgoing", Routes::bind(&RelationshipInstanceApi::get_outgoing_relationship_instances_by_relationship_type_of_entity_instance_handler, this));
    Routes::Get(*router, base + "/entities/instances/:entity_instance_uuid/relationships/outgoing", Routes::bind(&RelationshipInstanceApi::get_outgoing_relationship_instances_of_entity_instance_handler, this));
    Routes::Get(*router, base + "/relationships/instances/:relationship_instance_uuid", Routes::bind(&RelationshipInstanceApi::get_relationship_instance_handler, this));
    Routes::Get(*router, base + "/relationships/instances/start/:start_entity_instance_uuid/end/:end_entity_instance_uuid", Routes::bind(&RelationshipInstanceApi::get_relationship_instances_between_start_and_end_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&RelationshipInstanceApi::relationship_instance_api_default_handler, this));
}

void RelationshipInstanceApi::create_or_update_relationship_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto relationshipInstanceUuid = request.param(":relationshipInstanceUuid").as<std::string>();
    
    // Getting the body param
    
    RelationshipInstance relationshipInstance;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      relationshipInstance.fromJson(request_body);
    
      this->create_or_update_relationship_instance(relationshipInstanceUuid, relationshipInstance, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::create_relationship_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the body param
    
    RelationshipInstance relationshipInstance;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      relationshipInstance.fromJson(request_body);
    
      this->create_relationship_instance(relationshipInstance, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::delete_all_relationship_instances_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    try {
      this->delete_all_relationship_instances(response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::delete_relationship_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto relationshipInstanceUuid = request.param(":relationshipInstanceUuid").as<std::string>();
    
    try {
      this->delete_relationship_instance(relationshipInstanceUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::delete_relationship_instances_between_start_and_end_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto startEntityInstanceUuid = request.param(":startEntityInstanceUuid").as<std::string>();
    auto endEntityInstanceUuid = request.param(":endEntityInstanceUuid").as<std::string>();
    
    try {
      this->delete_relationship_instances_between_start_and_end(startEntityInstanceUuid, endEntityInstanceUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::get_all_relationship_instances_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    try {
      this->get_all_relationship_instances(response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::get_all_relationship_instances_by_relationship_type_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    auto relationshipTypeUuid = request.param(":relationshipTypeUuid").as<std::string>();
    
    try {
      this->get_all_relationship_instances_by_relationship_type_of_entity_instance(entityInstanceUuid, relationshipTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::get_all_relationship_instances_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    
    try {
      this->get_all_relationship_instances_of_entity_instance(entityInstanceUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::get_incoming_relationship_instances_by_relationship_type_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    auto relationshipTypeUuid = request.param(":relationshipTypeUuid").as<std::string>();
    
    try {
      this->get_incoming_relationship_instances_by_relationship_type_of_entity_instance(entityInstanceUuid, relationshipTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::get_incoming_relationship_instances_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    
    try {
      this->get_incoming_relationship_instances_of_entity_instance(entityInstanceUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::get_outgoing_relationship_instances_by_relationship_type_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    auto relationshipTypeUuid = request.param(":relationshipTypeUuid").as<std::string>();
    
    try {
      this->get_outgoing_relationship_instances_by_relationship_type_of_entity_instance(entityInstanceUuid, relationshipTypeUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::get_outgoing_relationship_instances_of_entity_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto entityInstanceUuid = request.param(":entityInstanceUuid").as<std::string>();
    
    try {
      this->get_outgoing_relationship_instances_of_entity_instance(entityInstanceUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::get_relationship_instance_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto relationshipInstanceUuid = request.param(":relationshipInstanceUuid").as<std::string>();
    
    try {
      this->get_relationship_instance(relationshipInstanceUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}
void RelationshipInstanceApi::get_relationship_instances_between_start_and_end_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto startEntityInstanceUuid = request.param(":startEntityInstanceUuid").as<std::string>();
    auto endEntityInstanceUuid = request.param(":endEntityInstanceUuid").as<std::string>();
    
    try {
      this->get_relationship_instances_between_start_and_end(startEntityInstanceUuid, endEntityInstanceUuid, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void RelationshipInstanceApi::relationship_instance_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

