# Enable C++ support
language: cpp

#we are going to use containers
sudo: true

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - python3-pip
            - python3-setuptools
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode10
      compiler: clang # use default compiler
      addons:
        homebrew:
          packages:
          - zstd
    - os: windows

#download python where necessary
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install conan ; fi # this is not ideal but ok

#install conan
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install conan  ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install conan    ; fi

#install dependencies and build
before_script:  
  - mkdir build
  - cd build
  - cmake ..
  - make

#execute the tests
script:
   - ls
   - cd bin
   - ls
   - ./inexor-entity-system-tests

notifications: # set notification options
  email:
    email: false