# Enable C++ support
language: cpp

#we are going to use containers
sudo: true

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
      compiler: clang # use default compiler
    - os: windows

#download python where necessary
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update             ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python3-pip ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install python              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install pip                 ; fi

#install conan
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install conan  ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install conan    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then pip install conan ; fi

#install dependencies and build
before_script:  
  - mkdir build
  - cd build
  - cmake ..
  - make

#execute the tests
script:
   - ls
   - cd bin
   - ls
   - ./inexor-entity-system-tests

notifications: # set notification options
  email:
    email: false