os: linux
    
services:
  - docker
    
sudo: required
    
language: general

matrix:
    include:
        - os: linux
          dist: xenial
          env:
          - DOCKER_IMAGE=rikorose/gcc-cmake:gcc-8 # GCC 8

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
