os: linux
    
services:
  - docker
    
sudo: required
    
matrix:
    include:
        - os: linux
          dist: xenial
          language: general
          env:
          - DOCKER_IMAGE=conanio/gcc8 # GCC 8
        - os: linux
          dist: xenial
          language: general
          env:
          - DOCKER_IMAGE=conanio/clang7 # clang 7

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
