os: linux
    
services:
  - docker
    
sudo: required
    
language: python
    
env:
  matrix:
    - DOCKER_IMAGE=conanio/gcc8 # 8.0

matrix:
    include:
        - os: osx
          osx_image: xcode10 # apple-clang 10.0
          language: generic
          env:

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
