os: linux
    
services:
  - docker
    
sudo: required
    
language: general

matrix:
    include:
        - os: linux
          dist: xenial
          env:
          - DOCKER_IMAGE=conanio/gcc8 # 8.0
        - os: linux
          dist: xenial
          env:
          - DOCKER_IMAGE=conanio/clang7 # 7.0

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
