# Enable C++ support
language: cpp

#we are going to use containers
sudo: false

cache:
  ccache: true
  directories:
    - $HOME/.ccache

os:
  - linux
  - osx
  - windows

dist: xenial # older build environments will likely fail because C++17

# add some cccache to make it faster
env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=200M
    - CCACHE_CPP2=1

#download python where necessary
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install python ; fi

#install conan
install:
  - pip3 install conan

#install dependencies and build
before_script:  
  - mkdir build
  - cd build
  - cmake ..
  - make

#execute the tests
script:
   - ls
   - cd bin
   - ls
   - ./inexor-entity-system-tests

notifications: # set notification options
  email:
    email: false