/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "RelationInstanceApi.hpp"


namespace inexor {
namespace entity_system {
namespace rest {
namespace api {


using namespace inexor::entity_system::rest::model;
using namespace xg;
using namespace restbed;
using namespace std;


RelationInstanceApi::RelationInstanceApi(
	std::shared_ptr<RelationInstanceApiRelationsInstancesRelation_instance_uuidResource> spRelationInstanceApiRelationsInstancesRelation_instance_uuidResource,
	std::shared_ptr<RelationInstanceApiRelationsInstancesResource> spRelationInstanceApiRelationsInstancesResource,
	std::shared_ptr<RelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource> spRelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource,
	std::shared_ptr<RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource> spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource,
	std::shared_ptr<RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource> spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource,
	std::shared_ptr<RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource> spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource,
	std::shared_ptr<RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource> spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource,
	std::shared_ptr<RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource> spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource,
	std::shared_ptr<RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource> spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource
) {
	this->spRelationInstanceApiRelationsInstancesRelation_instance_uuidResource = spRelationInstanceApiRelationsInstancesRelation_instance_uuidResource;
	this->spRelationInstanceApiRelationsInstancesResource = spRelationInstanceApiRelationsInstancesResource;
	this->spRelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource = spRelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource;
	this->spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource = spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource;
	this->spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource = spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource;
	this->spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource = spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource;
	this->spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource = spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource;
	this->spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource = spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource;
	this->spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource = spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource;
}

RelationInstanceApi::~RelationInstanceApi() {}

void RelationInstanceApi::publish_resources(std::shared_ptr<Service> service) {
	service->publish(spRelationInstanceApiRelationsInstancesRelation_instance_uuidResource);
	service->publish(spRelationInstanceApiRelationsInstancesResource);
	service->publish(spRelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource);
	service->publish(spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource);
	service->publish(spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource);
	service->publish(spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource);
	service->publish(spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource);
	service->publish(spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource);
	service->publish(spRelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource);
}

RelationInstanceApiRelationsInstancesRelation_instance_uuidResource::RelationInstanceApiRelationsInstancesRelation_instance_uuidResource(
	std::shared_ptr<inexor::entity_system::RelationInstanceManager> relation_instance_manager
)
{
	this->relation_instance_manager = relation_instance_manager;
	this->set_path("/relations/instances/{relation_instance_uuid: .*}/");
	this->set_method_handler("POST", std::bind(&RelationInstanceApiRelationsInstancesRelation_instance_uuidResource::POST_method_handler, this, std::placeholders::_1));
	this->set_method_handler("DELETE", std::bind(&RelationInstanceApiRelationsInstancesRelation_instance_uuidResource::DELETE_method_handler, this, std::placeholders::_1));
	this->set_method_handler("GET", std::bind(&RelationInstanceApiRelationsInstancesRelation_instance_uuidResource::GET_method_handler, this, std::placeholders::_1));
}

RelationInstanceApiRelationsInstancesRelation_instance_uuidResource::~RelationInstanceApiRelationsInstancesRelation_instance_uuidResource()
{
}

void RelationInstanceApiRelationsInstancesRelation_instance_uuidResource::POST_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();
	// Body params are present, therefore we have to fetch them
	int content_length = request->get_header("Content-Length", 0);
	session->fetch(content_length,
		[ this ]( const std::shared_ptr<restbed::Session> session, const restbed::Bytes & body )
		{

			const auto request = session->get_request();
			std::string requestBody = restbed::String::format("%.*s\n", ( int ) body.size( ), body.data( ));
			/**
			 * Get body params or form params here from the requestBody string
			 */
			
			// Getting the path params
			const std::string relation_instance_uuid = request->get_path_parameter("relation_instance_uuid", "");
			
			// Change the value of this variable to the appropriate response before sending the response
			int status_code = 200;
			
			/**
			 * Process the received information here
			 */
			
			if (status_code == 200) {
				session->close(200, "The created relation instance", { {"Connection", "close"} });
				return;
			}
			if (status_code == 0) {
				session->close(0, "unexpected error", { {"Connection", "close"} });
				return;
			}

		});
}

void RelationInstanceApiRelationsInstancesRelation_instance_uuidResource::DELETE_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const std::string relation_instance_uuid = request->get_path_parameter("relation_instance_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		std::shared_ptr<EntitySystemMessageDto> response = NULL;
		session->close(200, "Success message", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		std::shared_ptr<EntitySystemMessageDto> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}
void RelationInstanceApiRelationsInstancesRelation_instance_uuidResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const std::string relation_instance_uuid = request->get_path_parameter("relation_instance_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		std::shared_ptr<RelationInstanceDto> response = NULL;
		session->close(200, "The relation instance", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		std::shared_ptr<EntitySystemMessageDto> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}


RelationInstanceApiRelationsInstancesResource::RelationInstanceApiRelationsInstancesResource(
	std::shared_ptr<inexor::entity_system::RelationInstanceManager> relation_instance_manager
)
{
	this->relation_instance_manager = relation_instance_manager;
	this->set_path("/relations/instances/");
	this->set_method_handler("POST", std::bind(&RelationInstanceApiRelationsInstancesResource::POST_method_handler, this, std::placeholders::_1));
	this->set_method_handler("DELETE", std::bind(&RelationInstanceApiRelationsInstancesResource::DELETE_method_handler, this, std::placeholders::_1));
	this->set_method_handler("GET", std::bind(&RelationInstanceApiRelationsInstancesResource::GET_method_handler, this, std::placeholders::_1));
}

RelationInstanceApiRelationsInstancesResource::~RelationInstanceApiRelationsInstancesResource()
{
}

void RelationInstanceApiRelationsInstancesResource::POST_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();
	// Body params are present, therefore we have to fetch them
	int content_length = request->get_header("Content-Length", 0);
	session->fetch(content_length,
		[ this ]( const std::shared_ptr<restbed::Session> session, const restbed::Bytes & body )
		{

			const auto request = session->get_request();
			std::string requestBody = restbed::String::format("%.*s\n", ( int ) body.size( ), body.data( ));

			/**
			 * Get body params or form params here from the requestBody string
			 */
			
			// Change the value of this variable to the appropriate response before sending the response
			int status_code = 200;
			
			/**
			 * Process the received information here
			 */
			
			if (status_code == 200) {
				session->close(200, "The created relation instance", { {"Connection", "close"} });
				return;
			}
			if (status_code == 0) {
				session->close(0, "unexpected error", { {"Connection", "close"} });
				return;
			}

		});
}

void RelationInstanceApiRelationsInstancesResource::DELETE_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		std::shared_ptr<EntitySystemMessageDto> response = NULL;
		session->close(200, "Success message", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		std::shared_ptr<EntitySystemMessageDto> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}
void RelationInstanceApiRelationsInstancesResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		std::shared_ptr<RelationInstanceDto> response = NULL;
		session->close(200, "Array of relation instances", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		std::shared_ptr<EntitySystemMessageDto> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}


RelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource::RelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource(
	std::shared_ptr<inexor::entity_system::RelationInstanceManager> relation_instance_manager
)
{
	this->relation_instance_manager = relation_instance_manager;
	this->set_path("/relations/instances/start/{start_entity_instance_uuid: .*}/end/{end_entity_instance_uuid: .*}/");
	this->set_method_handler("DELETE", std::bind(&RelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource::DELETE_method_handler, this, std::placeholders::_1));
	this->set_method_handler("GET", std::bind(&RelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource::GET_method_handler, this, std::placeholders::_1));
}

RelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource::~RelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource()
{
}

void RelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource::DELETE_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();
			
	// Getting the path params
	const std::string start_entity_instance_uuid = request->get_path_parameter("start_entity_instance_uuid", "");
	const std::string end_entity_instance_uuid = request->get_path_parameter("end_entity_instance_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "Success message", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}

void RelationInstanceApiRelationsInstancesStartStart_entity_instance_uuidEndEnd_entity_instance_uuidResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const std::string start_entity_instance_uuid = request->get_path_parameter("start_entity_instance_uuid", "");
	const std::string end_entity_instance_uuid = request->get_path_parameter("end_entity_instance_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		std::shared_ptr<RelationInstanceDto> response = NULL;
		session->close(200, "Array of relation instances", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		std::shared_ptr<EntitySystemMessageDto> response = NULL;
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}


RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource::RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource(
	std::shared_ptr<inexor::entity_system::RelationInstanceManager> relation_instance_manager
)
{
	this->relation_instance_manager = relation_instance_manager;
	this->set_path("/entities/instances/{entity_instance_uuid: .*}/relations/{relation_type_uuid: .*}/");
	this->set_method_handler("GET", std::bind(&RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource::GET_method_handler, this, std::placeholders::_1));
}

RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource::~RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource()
{
}

void RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();
			
	// Getting the path params
	const std::string entity_instance_uuid = request->get_path_parameter("entity_instance_uuid", "");
	const std::string relation_type_uuid = request->get_path_parameter("relation_type_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "Array of relation instances", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}



RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource::RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource(
	std::shared_ptr<inexor::entity_system::RelationInstanceManager> relation_instance_manager
)
{
	this->relation_instance_manager = relation_instance_manager;
	this->set_path("/entities/instances/{entity_instance_uuid: .*}/relations/");
	this->set_method_handler("GET", std::bind(&RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource::GET_method_handler, this, std::placeholders::_1));
}

RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource::~RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource()
{
}

void RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();
			
	// Getting the path params
	const std::string entity_instance_uuid = request->get_path_parameter("entity_instance_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "Array of relation instances", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}



RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource::RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource(
	std::shared_ptr<inexor::entity_system::RelationInstanceManager> relation_instance_manager
)
{
	this->relation_instance_manager = relation_instance_manager;
	this->set_path("/entities/instances/{entity_instance_uuid: .*}/relations/{relation_type_uuid: .*}/incoming/");
	this->set_method_handler("GET", std::bind(&RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource::GET_method_handler, this, std::placeholders::_1));
}

RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource::~RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource()
{
}

void RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidIncomingResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();
			
	// Getting the path params
	const std::string entity_instance_uuid = request->get_path_parameter("entity_instance_uuid", "");
	const std::string relation_type_uuid = request->get_path_parameter("relation_type_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "Array of relation instances", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}



RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource::RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource(
	std::shared_ptr<inexor::entity_system::RelationInstanceManager> relation_instance_manager
)
{
	this->relation_instance_manager = relation_instance_manager;
	this->set_path("/entities/instances/{entity_instance_uuid: .*}/relations/incoming/");
	this->set_method_handler("GET", std::bind(&RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource::GET_method_handler, this, std::placeholders::_1));
}

RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource::~RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource()
{
}

void RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsIncomingResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();
			
	// Getting the path params
	const std::string entity_instance_uuid = request->get_path_parameter("entity_instance_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "Array of relation instances", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}



RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource::RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource(
	std::shared_ptr<inexor::entity_system::RelationInstanceManager> relation_instance_manager
)
{
	this->relation_instance_manager = relation_instance_manager;
	this->set_path("/entities/instances/{entity_instance_uuid: .*}/relations/{relation_type_uuid: .*}/outgoing/");
	this->set_method_handler("GET", std::bind(&RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource::GET_method_handler, this, std::placeholders::_1));
}

RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource::~RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource()
{
}

void RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsRelation_type_uuidOutgoingResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();

	// Getting the path params
	const std::string entity_instance_uuid = request->get_path_parameter("entity_instance_uuid", "");
	const std::string relation_type_uuid = request->get_path_parameter("relation_type_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "Array of relation instances", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}


RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource::RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource(
	std::shared_ptr<inexor::entity_system::RelationInstanceManager> relation_instance_manager
)
{
	this->relation_instance_manager = relation_instance_manager;
	this->set_path("/entities/instances/{entity_instance_uuid: .*}/relations/outgoing/");
	this->set_method_handler("GET", std::bind(&RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource::GET_method_handler, this, std::placeholders::_1));
}

RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource::~RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource()
{
}

void RelationInstanceApiEntitiesInstancesEntity_instance_uuidRelationsOutgoingResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();
			
	// Getting the path params
	const std::string entity_instance_uuid = request->get_path_parameter("entity_instance_uuid", "");

	// Change the value of this variable to the appropriate response before sending the response
	int status_code = 200;

	/**
	 * Process the received information here
	 */

	if (status_code == 200) {
		session->close(200, "Array of relation instances", { {"Connection", "close"} });
		return;
	}
	if (status_code == 0) {
		session->close(0, "unexpected error", { {"Connection", "close"} });
		return;
	}

}


}
}
}
}

