/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EntitySystemMessage.h
 *
 * 
 */

#ifndef EntitySystemMessage_H_
#define EntitySystemMessage_H_


#include "ModelBase.h"

#include <string>

namespace inexor {
namespace entity_system {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  EntitySystemMessage
    : public ModelBase
{
public:
    EntitySystemMessage();
    virtual ~EntitySystemMessage();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// EntitySystemMessage members

    /// <summary>
    /// 
    /// </summary>
    int32_t getCode() const;
    void setCode(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    std::string getMessage() const;
    void setMessage(std::string const& value);
    
protected:
    int32_t m_Code;

    std::string m_Message;

};

}
}
}
}

#endif /* EntitySystemMessage_H_ */
