/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EntitySystem.h
 *
 * 
 */

#ifndef EntitySystem_H_
#define EntitySystem_H_



#include "RelationshipType.h"
#include "RelationshipInstance.h"
#include "EntityType.h"
#include "EntityInstance.h"
#include <vector>
#include <memory>

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

/// <summary>
/// 
/// </summary>
class  EntitySystem
{
public:
    EntitySystem();
    virtual ~EntitySystem();
    
    std::string toJsonString();
    void fromJsonString(std::string const& jsonString);

    /////////////////////////////////////////////
    /// EntitySystem members
    
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<EntityType>> getEntityTypes() const;
    void setEntityTypes(std::vector<std::shared_ptr<EntityType>> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<RelationshipType>> getRelationshipTypes() const;
    void setRelationshipTypes(std::vector<std::shared_ptr<RelationshipType>> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<EntityInstance>> getEntityInstances() const;
    void setEntityInstances(std::vector<std::shared_ptr<EntityInstance>> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<RelationshipInstance>> getRelationshipInstances() const;
    void setRelationshipInstances(std::vector<std::shared_ptr<RelationshipInstance>> value);

protected:
    std::vector<std::shared_ptr<EntityType>> m_Entity_types;
    std::vector<std::shared_ptr<RelationshipType>> m_Relationship_types;
    std::vector<std::shared_ptr<EntityInstance>> m_Entity_instances;
    std::vector<std::shared_ptr<RelationshipInstance>> m_Relationship_instances;
};

}
}
}
}

#endif /* EntitySystem_H_ */
