/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EntityInstance.h
 *
 * 
 */

#ifndef EntityInstance_H_
#define EntityInstance_H_



#include <string>
#include "Attribute.h"
#include <vector>
#include <memory>

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

/// <summary>
/// 
/// </summary>
class  EntityInstance
{
public:
    EntityInstance();
    virtual ~EntityInstance();
    
    std::string toJsonString();
    void fromJsonString(std::string const& jsonString);

    /////////////////////////////////////////////
    /// EntityInstance members
    
    /// <summary>
    /// 
    /// </summary>
    std::string getEntityInstanceUuid() const;
    void setEntityInstanceUuid(std::string value);
    /// <summary>
    /// 
    /// </summary>
    std::string getEntityTypeUuid() const;
    void setEntityTypeUuid(std::string value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Attribute>> getAttributes() const;
    void setAttributes(std::vector<std::shared_ptr<Attribute>> value);

protected:
    std::string m_Entity_instance_uuid;
    std::string m_Entity_type_uuid;
    std::vector<std::shared_ptr<Attribute>> m_Attributes;
};

}
}
}
}

#endif /* EntityInstance_H_ */
