/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EntityInstance.h
 *
 * 
 */

#ifndef EntityInstance_H_
#define EntityInstance_H_


#include "ModelBase.h"

#include <string>
#include "Attribute.h"
#include <vector>

namespace inexor {
namespace entity_system {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  EntityInstance
    : public ModelBase
{
public:
    EntityInstance();
    virtual ~EntityInstance();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// EntityInstance members

    /// <summary>
    /// 
    /// </summary>
    std::string getEntityInstanceUuid() const;
    void setEntityInstanceUuid(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getEntityTypeUuid() const;
    void setEntityTypeUuid(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<Attribute>& getAttributes();
    
protected:
    std::string m_Entity_instance_uuid;

    std::string m_Entity_type_uuid;

    std::vector<Attribute> m_Attributes;

};

}
}
}
}

#endif /* EntityInstance_H_ */
