/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RelationshipInstance.h"

namespace inexor {
namespace entity_system {
namespace server {
namespace model {

RelationshipInstance::RelationshipInstance()
{
    m_Relationship_instance_uuid = "";
    m_Relationship_type_uuid = "";
    m_Start_node_entity_instance_uuid = "";
    m_End_node_entity_instance_uuid = "";
    
}

RelationshipInstance::~RelationshipInstance()
{
}

void RelationshipInstance::validate()
{
    // TODO: implement validation
}

nlohmann::json RelationshipInstance::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["relationship_instance_uuid"] = ModelBase::toJson(m_Relationship_instance_uuid);
    val["relationship_type_uuid"] = ModelBase::toJson(m_Relationship_type_uuid);
    val["start_node_entity_instance_uuid"] = ModelBase::toJson(m_Start_node_entity_instance_uuid);
    val["end_node_entity_instance_uuid"] = ModelBase::toJson(m_End_node_entity_instance_uuid);
    {
        nlohmann::json jsonArray;
        for( auto& item : m_Attributes )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val["attributes"] = jsonArray;
        
    }
    

    return val;
}

void RelationshipInstance::fromJson(const nlohmann::json& val)
{
    setRelationshipInstanceUuid(val.at("relationship_instance_uuid"));
    setRelationshipTypeUuid(val.at("relationship_type_uuid"));
    setStartNodeEntityInstanceUuid(val.at("start_node_entity_instance_uuid"));
    setEndNodeEntityInstanceUuid(val.at("end_node_entity_instance_uuid"));
    {
        m_Attributes.clear();
                    for( auto& item : val["attributes"] )
            {
                
                if(item.is_null())
                {
                    m_Attributes.push_back( Attribute() );
                }
                else
                {
                    Attribute newItem;
                    newItem.fromJson(item);
                    m_Attributes.push_back( newItem );
                }
                
            }
    }
    
}


std::string RelationshipInstance::getRelationshipInstanceUuid() const
{
    return m_Relationship_instance_uuid;
}
void RelationshipInstance::setRelationshipInstanceUuid(std::string const& value)
{
    m_Relationship_instance_uuid = value;
    
}
std::string RelationshipInstance::getRelationshipTypeUuid() const
{
    return m_Relationship_type_uuid;
}
void RelationshipInstance::setRelationshipTypeUuid(std::string const& value)
{
    m_Relationship_type_uuid = value;
    
}
std::string RelationshipInstance::getStartNodeEntityInstanceUuid() const
{
    return m_Start_node_entity_instance_uuid;
}
void RelationshipInstance::setStartNodeEntityInstanceUuid(std::string const& value)
{
    m_Start_node_entity_instance_uuid = value;
    
}
std::string RelationshipInstance::getEndNodeEntityInstanceUuid() const
{
    return m_End_node_entity_instance_uuid;
}
void RelationshipInstance::setEndNodeEntityInstanceUuid(std::string const& value)
{
    m_End_node_entity_instance_uuid = value;
    
}
std::vector<Attribute>& RelationshipInstance::getAttributes()
{
    return m_Attributes;
}

}
}
}
}

