/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RelationshipType.h
 *
 * 
 */

#ifndef RelationshipType_H_
#define RelationshipType_H_


#include "ModelBase.h"

#include <string>
#include "Attribute.h"
#include <vector>

namespace inexor {
namespace entity_system {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  RelationshipType
    : public ModelBase
{
public:
    RelationshipType();
    virtual ~RelationshipType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// RelationshipType members

    /// <summary>
    /// 
    /// </summary>
    std::string getRelationshipTypeUuid() const;
    void setRelationshipTypeUuid(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getStartNodeEntityTypeUuid() const;
    void setStartNodeEntityTypeUuid(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getEndNodeEntityTypeUuid() const;
    void setEndNodeEntityTypeUuid(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<Attribute>& getAttributes();
    
protected:
    std::string m_Relationship_type_uuid;

    std::string m_Name;

    std::string m_Start_node_entity_type_uuid;

    std::string m_End_node_entity_type_uuid;

    std::vector<Attribute> m_Attributes;

};

}
}
}
}

#endif /* RelationshipType_H_ */
