/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* EntityTypeApiImpl.h
*
* 
*/

#ifndef ENTITY_TYPE_API_IMPL_H_
#define ENTITY_TYPE_API_IMPL_H_


#include <memory>
#include <string>

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/optional.h>

#include "../api/EntityTypeApi.h"
#include "../model/Attribute.h"
#include "../model/EntityInstance.h"
#include "../model/EntitySystemMessage.h"
#include "../model/EntityType.h"
#include "../model/RelationshipType.h"

namespace inexor {
namespace entity_system {
namespace server {
namespace api {

using namespace inexor::entity_system::server::model;

class EntityTypeApiImpl : public inexor::entity_system::server::api::EntityTypeApi {
public:
    EntityTypeApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~EntityTypeApiImpl() {}

    void create_entity_type(Pistache::Http::ResponseWriter &response);
    void create_or_update_entity_type(const std::string &entityTypeUuid, const EntityType &entityType, Pistache::Http::ResponseWriter &response);
    void create_or_update_entity_type_attribute(const std::string &entityTypeUuid, const std::string &name, const std::string &body, Pistache::Http::ResponseWriter &response);
    void delete_all_instances_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void delete_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void delete_entity_type_attribute(const std::string &entityTypeUuid, const std::string &name, Pistache::Http::ResponseWriter &response);
    void delete_entity_types(Pistache::Http::ResponseWriter &response);
    void get_all_incoming_relationship_types_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_all_instances_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_all_outgoing_relationship_types_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_all_relationship_types_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_entity_type_attribute(const std::string &entityTypeUuid, const std::string &name, Pistache::Http::ResponseWriter &response);
    void get_entity_type_attributes(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void list_all_entity_types(Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif
