/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* EntityInstanceApiImpl.h
*
* 
*/

#ifndef ENTITY_INSTANCE_API_IMPL_H_
#define ENTITY_INSTANCE_API_IMPL_H_


#include <memory>
#include <string>

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/optional.h>

#include "../api/EntityInstanceApi.h"
#include "../model/Attribute.h"
#include "../model/EntityInstance.h"
#include "../model/EntitySystemMessage.h"
#include "../model/RelationshipInstance.h"

namespace inexor {
namespace entity_system {
namespace server {
namespace api {

using namespace inexor::entity_system::server::model;

class EntityInstanceApiImpl : public inexor::entity_system::server::api::EntityInstanceApi {
public:
    EntityInstanceApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~EntityInstanceApiImpl() {}

    void create_entity_instance(const EntityInstance &entityInstance, Pistache::Http::ResponseWriter &response);
    void create_or_update_entity_instance(const std::string &entityInstanceUuid, const EntityInstance &entityInstance, Pistache::Http::ResponseWriter &response);
    void create_or_update_entity_instance_attribute(const std::string &entityInstanceUuid, const std::string &name, const Attribute &attribute, Pistache::Http::ResponseWriter &response);
    void delete_all_entity_instances(Pistache::Http::ResponseWriter &response);
    void delete_entity_instance(const std::string &entityInstanceUuid, Pistache::Http::ResponseWriter &response);
    void delete_entity_instance_attribute(const std::string &entityInstanceUuid, const std::string &name, Pistache::Http::ResponseWriter &response);
    void delete_relationship_instances_between_start_and_end(const std::string &startEntityInstanceUuid, const std::string &endEntityInstanceUuid, Pistache::Http::ResponseWriter &response);
    void get_all_entity_instances(Pistache::Http::ResponseWriter &response);
    void get_all_relationship_instances_by_relationship_type_of_entity_instance(const std::string &entityInstanceUuid, const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_all_relationship_instances_of_entity_instance(const std::string &entityInstanceUuid, Pistache::Http::ResponseWriter &response);
    void get_entity_instance(const std::string &entityInstanceUuid, Pistache::Http::ResponseWriter &response);
    void get_entity_instance_attribute(const std::string &entityInstanceUuid, const std::string &name, Pistache::Http::ResponseWriter &response);
    void get_entity_instance_attributes(const std::string &entityInstanceUuid, Pistache::Http::ResponseWriter &response);
    void get_incoming_relationship_instances_by_relationship_type_of_entity_instance(const std::string &entityInstanceUuid, const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_incoming_relationship_instances_of_entity_instance(const std::string &entityInstanceUuid, Pistache::Http::ResponseWriter &response);
    void get_outgoing_relationship_instances_by_relationship_type_of_entity_instance(const std::string &entityInstanceUuid, const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_outgoing_relationship_instances_of_entity_instance(const std::string &entityInstanceUuid, Pistache::Http::ResponseWriter &response);
    void get_relationship_instances_between_start_and_end(const std::string &startEntityInstanceUuid, const std::string &endEntityInstanceUuid, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif
