/**
* Inexor Entity System
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 3.0.0
* Contact: info@inexor.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* RelationshipTypeApiImpl.h
*
* 
*/

#ifndef RELATIONSHIP_TYPE_API_IMPL_H_
#define RELATIONSHIP_TYPE_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/optional.h>
#include <memory>
#include <string>

#include "../api/RelationshipTypeApi.h"
#include "../model/EntitySystemMessage.h"
#include "../model/RelationshipInstance.h"
#include "../model/RelationshipType.h"

namespace inexor {
namespace entity_system {
namespace server {
namespace api {

using namespace inexor::entity_system::server::model;

class RelationshipTypeApiImpl : public inexor::entity_system::server::api::RelationshipTypeApi {
public:
    RelationshipTypeApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~RelationshipTypeApiImpl() {}

    void create_or_update_relationship_type(const std::string &relationshipTypeUuid, const RelationshipType &relationshipType, Pistache::Http::ResponseWriter &response);
    void create_relationship_type(const RelationshipType &relationshipType, Pistache::Http::ResponseWriter &response);
    void delete_all_relationship_types(Pistache::Http::ResponseWriter &response);
    void delete_relationship_type(const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_all_incoming_relationship_types_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_all_outgoing_relationship_types_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_all_relationship_instances_by_relationship_type_of_entity_instance(const std::string &entityInstanceUuid, const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_all_relationship_types(Pistache::Http::ResponseWriter &response);
    void get_all_relationship_types_of_entity_type(const std::string &entityTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_incoming_relationship_instances_by_relationship_type_of_entity_instance(const std::string &entityInstanceUuid, const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_outgoing_relationship_instances_by_relationship_type_of_entity_instance(const std::string &entityInstanceUuid, const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response);
    void get_relationship_type(const std::string &relationshipTypeUuid, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif
