/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#pragma once

#include <string>
#include <memory>

#include "entity-system/model/data/container/DataContainer.hpp"

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

	/// <summary>
	///
	/// </summary>
	class AttributeDto
	{
		public:
			AttributeDto();
			virtual ~AttributeDto();

			std::string to_json_string();
			void from_json_string(std::string const& json_string);

			/// <summary>
			///
			/// </summary>
			std::string get_attribute_uuid() const;
			void set_attribute_uuid(std::string attribute_uuid);

			/// <summary>
			///
			/// </summary>
			std::string get_name() const;
			void set_name(std::string name);

			/// <summary>
			///
			/// </summary>
			DataContainer get_value() const;
			void set_value(DataContainer value);

		protected:
			std::string attribute_uuid;
			std::string name;
			DataContainer value;
	};

}
}
}
}
