/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "AttributeDto.hpp"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

	AttributeDto::AttributeDto()
	{
		attribute_uuid = "";
		name = "";
		datatype = "";
		value = "";
	}

	AttributeDto::~AttributeDto()
	{
	}

	std::string AttributeDto::to_json_string()
	{
		std::stringstream ss;
		ptree pt;
		pt.put("attribute_uuid", attribute_uuid);
		pt.put("name", name);
		pt.put("datatype", datatype);
		pt.put("value", value);
		write_json(ss, pt, false);
		return ss.str();
	}

	void AttributeDto::from_json_string(std::string const& jsonString)
	{
		std::stringstream ss(jsonString);
		ptree pt;
		read_json(ss,pt);
		attribute_uuid = pt.get("attribute_uuid", "");
		name = pt.get("name", "");
		datatype = pt.get("datatype", "");
		value = pt.get("value", "");
	}

	std::string AttributeDto::get_attribute_uuid() const
	{
		return attribute_uuid;
	}

	void AttributeDto::set_attribute_uuid(std::string attribute_uuid)
	{
		this->attribute_uuid = attribute_uuid;
	}

	std::string AttributeDto::get_name() const
	{
		return name;
	}

	void AttributeDto::set_name(std::string name)
	{
		this->name = name;
	}

	std::string AttributeDto::get_datatype() const
	{
		return datatype;
	}

	void AttributeDto::set_datatype(std::string datatype)
	{
		this->datatype = datatype;
	}

	std::string AttributeDto::get_value() const
	{
		return value;
	}

	void AttributeDto::set_value(std::string value)
	{
		this->value = value;
	}

}
}
}
}

