/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "EntitySystemMessageDto.hpp"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

	EntitySystemMessageDto::EntitySystemMessageDto()
	{
		code = 0;
		message = "";
	}

	EntitySystemMessageDto::~EntitySystemMessageDto()
	{
	}

	std::string EntitySystemMessageDto::to_json_string()
	{
		std::stringstream ss;
		ptree pt;
		pt.put("code", code);
		pt.put("message", message);
		write_json(ss, pt, false);
		return ss.str();
	}

	void EntitySystemMessageDto::from_json_string(std::string const& jsonString)
	{
		std::stringstream ss(jsonString);
		ptree pt;
		read_json(ss,pt);
		code = pt.get("code", 0);
		message = pt.get("message", "");
	}

	int32_t EntitySystemMessageDto::getCode() const
	{
		return code;
	}

	void EntitySystemMessageDto::setCode(int32_t value)
	{
		this->code = value;
	}

	std::string EntitySystemMessageDto::getMessage() const
	{
		return message;
	}

	void EntitySystemMessageDto::setMessage(std::string value)
	{
		this->message = value;
	}

}
}
}
}

