/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "EntityTypeDto.hpp"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

	EntityTypeDto::EntityTypeDto()
	{
		m_Entity_type_uuid = "";
		m_Name = "";

	}

	EntityTypeDto::~EntityTypeDto()
	{
	}

	std::string EntityTypeDto::toJsonString()
	{
		std::stringstream ss;
		ptree pt;
		pt.put("entity_type_uuid", m_Entity_type_uuid);
		pt.put("name", m_Name);
		write_json(ss, pt, false);
		return ss.str();
	}

	void EntityTypeDto::fromJsonString(std::string const& jsonString)
	{
		std::stringstream ss(jsonString);
		ptree pt;
		read_json(ss,pt);
		m_Entity_type_uuid = pt.get("entity_type_uuid", "");
		m_Name = pt.get("name", "");
	}

	std::string EntityTypeDto::getEntityTypeUuid() const
	{
		return m_Entity_type_uuid;
	}

	void EntityTypeDto::setEntityTypeUuid(std::string value)
	{
		m_Entity_type_uuid = value;
	}

	std::string EntityTypeDto::getName() const
	{
		return m_Name;
	}

	void EntityTypeDto::setName(std::string value)
	{
		m_Name = value;
	}

	std::vector<std::shared_ptr<AttributeDto>> EntityTypeDto::getAttributes() const
	{
		return m_Attributes;
	}

	void EntityTypeDto::setAttributes(std::vector<std::shared_ptr<AttributeDto>> value)
	{
		m_Attributes = value;
	}

}
}
}
}

