/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#pragma once

#include <string>
#include <vector>
#include <memory>

#include "AttributeDto.hpp"

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

	/// <summary>
	///
	/// </summary>
	class  EntityInstanceDto
	{
		public:
			EntityInstanceDto();
			virtual ~EntityInstanceDto();

			std::string toJsonString();
			void fromJsonString(std::string const& jsonString);

			/// <summary>
			///
			/// </summary>
			std::string getEntityInstanceUuid() const;
			void setEntityInstanceUuid(std::string value);

			/// <summary>
			///
			/// </summary>
			std::string getEntityTypeUuid() const;
			void setEntityTypeUuid(std::string value);

			/// <summary>
			///
			/// </summary>
			std::vector<std::shared_ptr<AttributeDto>> getAttributes() const;
			void setAttributes(std::vector<std::shared_ptr<AttributeDto>> value);

		protected:
			std::string m_Entity_instance_uuid;
			std::string m_Entity_type_uuid;
			std::vector<std::shared_ptr<AttributeDto>> m_Attributes;
	};

}
}
}
}
