/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#pragma once

#include <vector>
#include <memory>

#include "EntityInstance.hpp"
#include "EntityType.hpp"
#include "RelationInstance.hpp"
#include "RelationType.hpp"

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

/// <summary>
/// 
/// </summary>
class  EntitySystem
{
public:
    EntitySystem();
    virtual ~EntitySystem();
    
    std::string toJsonString();
    void fromJsonString(std::string const& jsonString);

    /////////////////////////////////////////////
    /// EntitySystem members
    
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<EntityType>> getEntityTypes() const;
    void setEntityTypes(std::vector<std::shared_ptr<EntityType>> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<RelationType>> getRelationTypes() const;
    void setRelationTypes(std::vector<std::shared_ptr<RelationType>> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<EntityInstance>> getEntityInstances() const;
    void setEntityInstances(std::vector<std::shared_ptr<EntityInstance>> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<RelationInstance>> getRelationInstances() const;
    void setRelationInstances(std::vector<std::shared_ptr<RelationInstance>> value);

protected:
    std::vector<std::shared_ptr<EntityType>> m_Entity_types;
    std::vector<std::shared_ptr<RelationType>> m_Relation_types;
    std::vector<std::shared_ptr<EntityInstance>> m_Entity_instances;
    std::vector<std::shared_ptr<RelationInstance>> m_Relation_instances;
};

}
}
}
}
