/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "RelationType.hpp"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

RelationType::RelationType()
{
    m_Relation_type_uuid = "";
    m_Name = "";
    m_Start_node_entity_type_uuid = "";
    m_End_node_entity_type_uuid = "";
    
}

RelationType::~RelationType()
{
}

std::string RelationType::toJsonString()
{
	std::stringstream ss;
	ptree pt;
	pt.put("relation_type_uuid", m_Relation_type_uuid);
	pt.put("name", m_Name);
	pt.put("start_node_entity_type_uuid", m_Start_node_entity_type_uuid);
	pt.put("end_node_entity_type_uuid", m_End_node_entity_type_uuid);
	write_json(ss, pt, false);
	return ss.str();
}

void RelationType::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	m_Relation_type_uuid = pt.get("relation_type_uuid", "");
	m_Name = pt.get("name", "");
	m_Start_node_entity_type_uuid = pt.get("start_node_entity_type_uuid", "");
	m_End_node_entity_type_uuid = pt.get("end_node_entity_type_uuid", "");
}

std::string RelationType::getRelationTypeUuid() const
{
    return m_Relation_type_uuid;
}
void RelationType::setRelationTypeUuid(std::string value)
{
    m_Relation_type_uuid = value;
}
std::string RelationType::getName() const
{
    return m_Name;
}
void RelationType::setName(std::string value)
{
    m_Name = value;
}
std::string RelationType::getStartNodeEntityTypeUuid() const
{
    return m_Start_node_entity_type_uuid;
}
void RelationType::setStartNodeEntityTypeUuid(std::string value)
{
    m_Start_node_entity_type_uuid = value;
}
std::string RelationType::getEndNodeEntityTypeUuid() const
{
    return m_End_node_entity_type_uuid;
}
void RelationType::setEndNodeEntityTypeUuid(std::string value)
{
    m_End_node_entity_type_uuid = value;
}
std::vector<std::shared_ptr<Attribute>> RelationType::getAttributes() const
{
    return m_Attributes;
}
void RelationType::setAttributes(std::vector<std::shared_ptr<Attribute>> value)
{
    m_Attributes = value;
}

}
}
}
}

