/**
 * Inexor Entity System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@inexor.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RelationshipType.h
 *
 * 
 */

#ifndef RelationshipType_H_
#define RelationshipType_H_

#include <string>
#include <vector>
#include <memory>

#include "Attribute.hpp"

namespace inexor {
namespace entity_system {
namespace rest {
namespace model {

/// <summary>
/// 
/// </summary>
class  RelationshipType
{
public:
    RelationshipType();
    virtual ~RelationshipType();
    
    std::string toJsonString();
    void fromJsonString(std::string const& jsonString);

    /////////////////////////////////////////////
    /// RelationshipType members
    
    /// <summary>
    /// 
    /// </summary>
    std::string getRelationshipTypeUuid() const;
    void setRelationshipTypeUuid(std::string value);
    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string value);
    /// <summary>
    /// 
    /// </summary>
    std::string getStartNodeEntityTypeUuid() const;
    void setStartNodeEntityTypeUuid(std::string value);
    /// <summary>
    /// 
    /// </summary>
    std::string getEndNodeEntityTypeUuid() const;
    void setEndNodeEntityTypeUuid(std::string value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Attribute>> getAttributes() const;
    void setAttributes(std::vector<std::shared_ptr<Attribute>> value);

protected:
    std::string m_Relationship_type_uuid;
    std::string m_Name;
    std::string m_Start_node_entity_type_uuid;
    std::string m_End_node_entity_type_uuid;
    std::vector<std::shared_ptr<Attribute>> m_Attributes;
};

}
}
}
}

#endif /* RelationshipType_H_ */
