// Inexor entity system prototype
// (c)2018 Inexor

#ifndef INEXOR_ENTSYS_RESULT_CODE_ENUM_HEADER
#define INEXOR_ENTSYS_RESULT_CODE_ENUM_HEADER


namespace inexor {
namespace entity_system {


	// 
	enum ENTSYS_RETURN_CODE
    {
        ENTSYS_RETURN_ERROR = -1000,
        ENTSYS_RETURN_ERROR_ENTITY_TYPE_ALREADY_EXISTS,
        ENTSYS_RETURN_ERROR_ENTITY_TYPE_NOT_FOUND,
        ENTSYS_RETURN_ERROR_INVALID_NAME,
        ENTSYS_RETURN_SUCCESS = 1,
    };


};
};

#endif // INEXOR_ENTSYS_RESULT_CODE_ENUM_HEADER
